<?php
//Secuencia actual = 81
//Iniciar nueva con 82

//Constantes de funciones generales
define('CONS_FUNC_LOGIN',1);
define('CONS_FUNC_LOGOUT',2);

//Constantes de funciones principales
define('CONS_FUNC_ADMINISTRACION',3);
define('CONS_FUNC_CURSOS',4);
define('CONS_FUNC_CATEDRATICOS',5);
define('CONS_FUNC_ESTUDIANTES',6);

//Constantes de funciones ADM
define('CONS_FUNC_ADM_GESTIONUSUARIO',7);
define('CONS_FUNC_ADM_CONSULTARUSUARIO',8);
define('CONS_FUNC_ADM_CREARUSUARIO',9);
define('CONS_FUNC_ADM_MODIFICARUSUARIO',10);
define('CONS_FUNC_ADM_ELIMINARUSUARIO',11);

define('CONS_FUNC_ADM_GESTIONPARAMETRO',12);
define('CONS_FUNC_ADM_CONSULTARPARAMETRO',13);
define('CONS_FUNC_ADM_CREARPARAMETRO',14);
define('CONS_FUNC_ADM_MODIFICARPARAMETRO',15);
define('CONS_FUNC_ADM_ELIMINARPARAMETRO',16);

define('CONS_FUNC_ADM_GESTIONEDIFICIO',17);
define('CONS_FUNC_ADM_CONSULTAREDIFICIO',18);
define('CONS_FUNC_ADM_CREAREDIFICIO',19);
define('CONS_FUNC_ADM_MODIFICAREDIFICIO',20);
define('CONS_FUNC_ADM_ELIMINAREDIFICIO',21);

define('CONS_FUNC_ADM_GESTIONASIGNACIONEDIFICIO',52);
define('CONS_FUNC_ADM_CONSULTARASIGNACIONEDIFICIO',53);
define('CONS_FUNC_ADM_CREARASIGNACIONEDIFICIO',54);
define('CONS_FUNC_ADM_MODIFICARASIGNACIONEDIFICIO',55);
define('CONS_FUNC_ADM_ELIMINARASIGNACIONEDIFICIO',56);

define('CONS_FUNC_ADM_GESTIONPERIODO',62);
define('CONS_FUNC_ADM_CONSULTAPERIODO',63);
define('CONS_FUNC_ADM_CREARPERIODO',64);
define('CONS_FUNC_ADM_MODIFICARPERIODO',65);
define('CONS_FUNC_ADM_ELIMINARPERIODO',66);

define('CONS_FUNC_ADM_GESTIONCENTROUNIDAD',67);
define('CONS_FUNC_ADM_CONSULTACENTROUNIDAD',68);
define('CONS_FUNC_ADM_CREARCENTROUNIDAD',69);
define('CONS_FUNC_ADM_MODIFICARCENTROUNIDAD',70);
define('CONS_FUNC_ADM_ELIMINARCENTROUNIDAD',71);

define('CONS_FUNC_ADM_GESTIONUNIDAD',72);
define('CONS_FUNC_ADM_CONSULTAUNIDAD',73);
define('CONS_FUNC_ADM_CREARUNIDAD',74);
define('CONS_FUNC_ADM_MODIFICARUNIDAD',75);
define('CONS_FUNC_ADM_ELIMINARUNIDAD',76);


//Constantes de funciones CUR
define('CONS_FUNC_CUR_GESTIONCURSO',22);
define('CONS_FUNC_CUR_CONSULTARCURSO',23);
define('CONS_FUNC_CUR_CREARCURSO',24);
define('CONS_FUNC_CUR_MODIFICARCURSO',25);
define('CONS_FUNC_CUR_ELIMINARCURSO',26);

define('CONS_FUNC_CUR_GESTIONSECCION',27);
define('CONS_FUNC_CUR_CONSULTARSECCION',28);
define('CONS_FUNC_CUR_CREARSECCION',29);
define('CONS_FUNC_CUR_MODIFICARSECCION',30);
define('CONS_FUNC_CUR_ELIMINARSECCION',31);

define('CONS_FUNC_CUR_GESTIONPENSUM',32);
define('CONS_FUNC_CUR_CONSULTARPENSUM',33);
define('CONS_FUNC_CUR_CREARPENSUM',34);
define('CONS_FUNC_CUR_MODIFICARPENSUM',35);
define('CONS_FUNC_CUR_ELIMINARPENSUM',36);

define('CONS_FUNC_CUR_GESTIONCARRERA',37);
define('CONS_FUNC_CUR_CONSULTARCARRERA',38);
define('CONS_FUNC_CUR_CREARCARRERA',39);
define('CONS_FUNC_CUR_MODIFICARCARRERA',40);
define('CONS_FUNC_CUR_ELIMINARCARRERA',41);

define('CONS_FUNC_CUR_GESTIONHORARIO',42);
define('CONS_FUNC_CUR_CONSULTARHORARIO',43);
define('CONS_FUNC_CUR_CREARHORARIO',44);
define('CONS_FUNC_CUR_MODIFICARHORARIO',45);
define('CONS_FUNC_CUR_ELIMINARHORARIO',46);

define('CONS_FUNC_CUR_GESTIONNOTA',47);
define('CONS_FUNC_CUR_CONSULTARNOTA',48);
define('CONS_FUNC_CUR_CREARNOTA',49);
define('CONS_FUNC_CUR_MODIFICARNOTA',50);
define('CONS_FUNC_CUR_ELIMINARNOTA',51);

define('CONS_FUNC_CUR_GESTIONSALON',57);
define('CONS_FUNC_CUR_CONSULTASALON',58);
define('CONS_FUNC_CUR_CREARSALON',59);
define('CONS_FUNC_CUR_MODIFICARSALON',60);
define('CONS_FUNC_CUR_ELIMINARSALON',61);

define('CONS_FUNC_CUR_GESTIONCURSOPENSUM',77);
define('CONS_FUNC_CUR_CONSULTARCURSOPENSUM',78);
define('CONS_FUNC_CUR_CREARCURSOPENSUM',79);
define('CONS_FUNC_CUR_MODIFICARCURSOPENSUM',80);
define('CONS_FUNC_CUR_ELIMINARCURSOPENSUM',81);

define('CONS_FUNC_CUR_GESTIONCICLO',82);
define('CONS_FUNC_CUR_CONSULTARCICLO',83);
define('CONS_FUNC_CUR_CREARCICLO',84);
define('CONS_FUNC_CUR_MODIFICARCICLO',85);
define('CONS_FUNC_CUR_ELIMINARCICLO',86);


//Constantes de funciones CAT


//Constantes de funciones EST
?>
