<?php

//Constantes de funciones generales
define('CONS_FUNC_LOGIN',1);
define('CONS_FUNC_LOGOUT',2);

//Constantes de funciones ADM
define('CONS_FUNC_ADM_GESTIONUSUARIO',3);
define('CONS_FUNC_ADM_CONSULTARUSUARIO',4);
define('CONS_FUNC_ADM_CREARUSUARIO',5);
define('CONS_FUNC_ADM_MODIFICARUSUARIO',6);
define('CONS_FUNC_ADM_ELIMINARUSUARIO',7);

define('CONS_FUNC_ADM_GESTIONPARAMETRO',8);
define('CONS_FUNC_ADM_CONSULTARPARAMETRO',9);
define('CONS_FUNC_ADM_CREARPARAMETRO',10);
define('CONS_FUNC_ADM_MODIFICARPARAMETRO',11);
define('CONS_FUNC_ADM_ELIMINARPARAMETRO',12);

define('CONS_FUNC_ADM_GESTIONCURSO',13);
define('CONS_FUNC_ADM_CONSULTARCURSO',14);
define('CONS_FUNC_ADM_CREARCURSO',15);
define('CONS_FUNC_ADM_MODIFICARCURSO',16);
define('CONS_FUNC_ADM_ELIMINARCURSO',17);

define('CONS_FUNC_ADM_GESTIONSECCION',18);
define('CONS_FUNC_ADM_CONSULTARSECCION',19);
define('CONS_FUNC_ADM_CREARSECCION',20);
define('CONS_FUNC_ADM_MODIFICARSECCION',21);
define('CONS_FUNC_ADM_ELIMINARSECCION',22);

define('CONS_FUNC_ADM_GESTIONCARRERA',23);
define('CONS_FUNC_ADM_CONSULTARCARRERA',24);
define('CONS_FUNC_ADM_CREARCARRERA',25);
define('CONS_FUNC_ADM_MODIFICARCARRERA',26);
define('CONS_FUNC_ADM_ELIMINARCARRERA',27);

define('CONS_FUNC_ADM_GESTIONHORARIO',28);
define('CONS_FUNC_ADM_CONSULTARHORARIO',29);
define('CONS_FUNC_ADM_CREARHORARIO',30);
define('CONS_FUNC_ADM_MODIFICARHORARIO',31);
define('CONS_FUNC_ADM_ELIMINARHORARIO',32);

//Constantes de funciones CAT
define('CONS_FUNC_CAT_GESTIONNOTA',33);
define('CONS_FUNC_CAT_CONSULTARNOTA',34);
define('CONS_FUNC_CAT_CREARNOTA',35);
define('CONS_FUNC_CAT_MODIFICARNOTA',36);
define('CONS_FUNC_CAT_ELIMINARNOTA',37);

?>
