<?php

//Constantes de funciones generales
define('CONS_FUNC_LOGIN',1);
define('CONS_FUNC_LOGOUT',2);

//Constantes de funciones principales
define('CONS_FUNC_ADMINISTRACION',3);
define('CONS_FUNC_CURSOS',4);
define('CONS_FUNC_CATEDRATICOS',5);
define('CONS_FUNC_ESTUDIANTES',6);

//Constantes de funciones ADM
define('CONS_FUNC_ADM_GESTIONUSUARIO',7);
define('CONS_FUNC_ADM_CONSULTARUSUARIO',8);
define('CONS_FUNC_ADM_CREARUSUARIO',9);
define('CONS_FUNC_ADM_MODIFICARUSUARIO',10);
define('CONS_FUNC_ADM_ELIMINARUSUARIO',11);

define('CONS_FUNC_ADM_GESTIONPARAMETRO',12);
define('CONS_FUNC_ADM_CONSULTARPARAMETRO',13);
define('CONS_FUNC_ADM_CREARPARAMETRO',14);
define('CONS_FUNC_ADM_MODIFICARPARAMETRO',15);
define('CONS_FUNC_ADM_ELIMINARPARAMETRO',16);

define('CONS_FUNC_ADM_GESTIONEDIFICIO',17);
define('CONS_FUNC_ADM_CONSULTAREDIFICIO',18);
define('CONS_FUNC_ADM_CREAREDIFICIO',19);
define('CONS_FUNC_ADM_MODIFICAREDIFICIO',20);
define('CONS_FUNC_ADM_ELIMINAREDIFICIO',21);


//Constantes de funciones CUR
define('CONS_FUNC_CUR_GESTIONCURSO',22);
define('CONS_FUNC_CUR_CONSULTARCURSO',23);
define('CONS_FUNC_CUR_CREARCURSO',24);
define('CONS_FUNC_CUR_MODIFICARCURSO',25);
define('CONS_FUNC_CUR_ELIMINARCURSO',26);

define('CONS_FUNC_CUR_GESTIONSECCION',27);
define('CONS_FUNC_CUR_CONSULTARSECCION',28);
define('CONS_FUNC_CUR_CREARSECCION',29);
define('CONS_FUNC_CUR_MODIFICARSECCION',30);
define('CONS_FUNC_CUR_ELIMINARSECCION',31);

define('CONS_FUNC_CUR_GESTIONPENSUM',32);
define('CONS_FUNC_CUR_CONSULTARPENSUM',33);
define('CONS_FUNC_CUR_CREARPENSUM',34);
define('CONS_FUNC_CUR_MODIFICARPENSUM',35);
define('CONS_FUNC_CUR_ELIMINARPENSUM',36);

define('CONS_FUNC_CUR_GESTIONCARRERA',37);
define('CONS_FUNC_CUR_CONSULTARCARRERA',38);
define('CONS_FUNC_CUR_CREARCARRERA',39);
define('CONS_FUNC_CUR_MODIFICARCARRERA',40);
define('CONS_FUNC_CUR_ELIMINARCARRERA',41);

define('CONS_FUNC_CUR_GESTIONHORARIO',42);
define('CONS_FUNC_CUR_CONSULTARHORARIO',43);
define('CONS_FUNC_CUR_CREARHORARIO',44);
define('CONS_FUNC_CUR_MODIFICARHORARIO',45);
define('CONS_FUNC_CUR_ELIMINARHORARIO',46);

define('CONS_FUNC_CUR_GESTIONNOTA',47);
define('CONS_FUNC_CUR_CONSULTARNOTA',48);
define('CONS_FUNC_CUR_CREARNOTA',49);
define('CONS_FUNC_CUR_MODIFICARNOTA',50);
define('CONS_FUNC_CUR_ELIMINARNOTA',51);


//Constantes de funciones CAT


//Constantes de funciones EST
?>
