<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Description of Parametros
 *
 * @author ARIAS
 */
//Constantes de parámetros de tipo aplicación
define('CONS_PARAM_APP_MAXREINTENTOS',1);
define('CONS_PARAM_APP_MAXTIEMPOSESIONACTIVA',2);
define('CONS_PARAM_APP_MAXINTENTOSASIGN',3);

//Constantes de parámetros de tipo centro - unidad académica
define('CONS_PARAM_CENTROUNIDAD_TIPOCICLO',100);
define('CONS_PARAM_UNIDAD_NOTAPROMOCION',101);
define('CONS_PARAM_UNIDAD_NOTATOTALZONA',102);
define('CONS_PARAM_UNIDAD_NOTAEXAMENFINAL',103);
define('CONS_PARAM_UNIDAD_NOTAZONAMINIMA',104);
define('CONS_PARAM_UNIDAD_NOTASUFICIENCIA',105);
define('CONS_PARAM_UNIDAD_NOTAEXAMENFINALMINIMA',106);

//Constantes de parámetros de tipo carrera
define('CONS_PARAM_CARRERA_MAXCURSOSTRASLAPADOS',200);
define('CONS_PARAM_CARRERA_MAXTIEMPOTRASLAPE',201);
define('CONS_PARAM_CARRERA_CRITERIOTIEMPOTRASLAPE',202);
define('CONS_PARAM_CARRERA_MAXASIGNPORCURSO',203);
define('CONS_PARAM_CARRERA_MAXCUPOPORSECCIONCURSO',204);
define('CONS_PARAM_CARRERA_MAXCURSOSAASIGNARPORCICLO',205);

?>
